import { ArchiveIcon } from '@/icons/archive';
import { ArrowLeftIcon } from '@/icons/arrow-left';
import { ArrowRightIcon } from '@/icons/arrow-right';
import { AtSignIcon } from '@/icons/at-sign';
import { BadgePercentIcon } from '@/icons/badge-percent';
import { BellIcon } from '@/icons/bell';
import { BoldIcon } from '@/icons/bold';
import { CalendarCogIcon } from '@/icons/calendar-cog';
import { ChartPieIcon } from '@/icons/chart-pie';
import { CircleDollarSignIcon } from '@/icons/circle-dollar-sign';
import { CopyIcon } from '@/icons/copy';
import { CursorClickIcon } from '@/icons/cursor-click';
import { DeleteIcon } from '@/icons/delete';
import { DownloadIcon } from '@/icons/download';
import { DownvoteIcon } from '@/icons/downvote';
import { EditIcon } from '@/icons/edit';
import { ExpandIcon } from '@/icons/expand';
import { FilePenLineIcon } from '@/icons/file-pen-line';
import { FileStackIcon } from '@/icons/file-stack';
import { FingerprintIcon } from '@/icons/fingerprint';
import { GitPullRequestIcon } from '@/icons/git-pull-request';
import { GridIcon } from '@/icons/grid';
import { HandCoinsIcon } from '@/icons/hand-coins';
import { HomeIcon } from '@/icons/home';
import { ItalicIcon } from '@/icons/italic';
import { LanguagesIcon } from '@/icons/languages';
import { LayersIcon } from '@/icons/layers';
import { LinkIcon } from '@/icons/link';
import { PartyPopperIcon } from '@/icons/party-popper';
import { PenToolIcon } from '@/icons/pen-tool';
import { RefreshIcon } from '@/icons/refresh';
import { RouteIcon } from '@/icons/route';
import { ScanTextIcon } from '@/icons/scan-text';
import { SettingsIcon } from '@/icons/settings';
import { SettingsGearIcon } from '@/icons/settings-gear';
import { SunIcon } from '@/icons/sun';
import { UnderlineIcon } from '@/icons/underline';
import { UndoIcon } from '@/icons/undo';
import { UnplugIcon } from '@/icons/unplug';
import { UpvoteIcon } from '@/icons/upvote';
import { UsersIcon } from '@/icons/users';
import { VolumeIcon } from '@/icons/volume';
import { AttachFileIcon } from '@/icons/attach-file';
import { GaugeIcon } from '@/icons/gauge';
import { MenuIcon } from '@/icons/menu';
import { ClockIcon } from '@/icons/clock';

const ICON_LIST = [
  { name: 'home', icon: HomeIcon },
  { name: 'arrow-left', icon: ArrowLeftIcon },
  { name: 'arrow-right', icon: ArrowRightIcon },
  { name: 'expand', icon: ExpandIcon },
  { name: 'route', icon: RouteIcon },
  { name: 'refresh', icon: RefreshIcon },
  { name: 'undo', icon: UndoIcon },
  { name: 'download', icon: DownloadIcon },
  { name: 'edit', icon: EditIcon },
  { name: 'delete', icon: DeleteIcon },
  { name: 'settings', icon: SettingsIcon },
  { name: 'settings-gear', icon: SettingsGearIcon },
  { name: 'calendar-cog', icon: CalendarCogIcon },
  { name: 'cursor-click', icon: CursorClickIcon },
  { name: 'menu', icon: MenuIcon },
  { name: 'clock', icon: ClockIcon },
  { name: 'file-stack', icon: FileStackIcon },
  { name: 'file-pen-line', icon: FilePenLineIcon },
  { name: 'archive', icon: ArchiveIcon },
  { name: 'copy', icon: CopyIcon },
  { name: 'attach-file', icon: AttachFileIcon },
  { name: 'bold', icon: BoldIcon },
  { name: 'italic', icon: ItalicIcon },
  { name: 'underline', icon: UnderlineIcon },
  { name: 'scan-text', icon: ScanTextIcon },
  { name: 'languages', icon: LanguagesIcon },
  { name: 'at-sign', icon: AtSignIcon },
  { name: 'bell', icon: BellIcon },
  { name: 'users', icon: UsersIcon },
  { name: 'upvote', icon: UpvoteIcon },
  { name: 'downvote', icon: DownvoteIcon },
  { name: 'circle-dollar-sign', icon: CircleDollarSignIcon },
  { name: 'hand-coins', icon: HandCoinsIcon },
  { name: 'badge-percent', icon: BadgePercentIcon },
  { name: 'chart-pie', icon: ChartPieIcon },
  { name: 'gauge', icon: GaugeIcon },
  { name: 'pen-tool', icon: PenToolIcon },
  { name: 'fingerprint', icon: FingerprintIcon },
  { name: 'link', icon: LinkIcon },
  { name: 'layers', icon: LayersIcon },
  { name: 'grid', icon: GridIcon },
  { name: 'git-pull-request', icon: GitPullRequestIcon },
  { name: 'unplug', icon: UnplugIcon },
  { name: 'volume', icon: VolumeIcon },
  { name: 'sun', icon: SunIcon },
  { name: 'party-popper', icon: PartyPopperIcon },
];

export { ICON_LIST };
